### ISSUE TITLE
History manipulation

### ISSUE THREAD

**Issue by sesas** [donnemartin/saws#20]
Feature request: use saws autocompletion but delegate execution of the command to bash or the underlining shell. 

For example, right now this cmd doesn't work:  
  `aws s3 ls | less`

There are use cases in which you would want to manipulate the output of an `aws` cmd. 

Also it would be nice if the cmds executed in saws were to end up in the history file so that they can be manipulated at a later time.  Especially since that there's no way of getting the saws history. 

Thanks for this project.

**Comment by donnemartin** [comment]
Hi Gabriel,

`SAWS` supports some piping of commands, but more support would be great.  The underlying shell does execute the command, but some more work needs to be done.

See the following duplicate issue:  https://github.com/donnemartin/saws/issues/17

Regarding history, you can use the up/down arrow keys while running `SAWS` to access it.  The history location is specified in `~/.sawsrc` and defaults to `~/.saws-history`.  

Are you looking to have it go to say, '~./bash_history`?

-Donne

**Comment by sesas** [comment]
that was my initial thought, have all cmds go to `~/.bash_history`, but I didn't know the cmds were saved to `~/.saws-history`.  Maybe there could be an option to send the history to both? 

Or maybe the autocomplete logic could moved to a `complete` cmd, so that each shell can use it, keeping the other facilities intact (piping, history, aliasing, etc).

**Comment by donnemartin** [comment]
Renamed to "History manipulation".  Tracking piping request here: https://github.com/donnemartin/saws/issues/17.

**Comment by donnemartin** [comment]
Quick investigation: 

Using `~/.bash_history` has some issues.  It seems the shell is treating the history differently probably because `SAWS` is a Python program and its commands are executed in a `subprocess` call.  I had to restart the shell with `exec bash -l` to see the commands executed in `SAWS`.

`SAWS` history relies on `FileHistory` from `prompt-toolkit`, which also would need some tweaks.

**Comment by donnemartin** [comment]
@sesas because of the issues described above, I don't think I plan on making `SAWS` compatible with `~/.bash_history` at this time.  If there is more interest I'd be happy to reconsider in the future.

Thanks for pointing out that the command history feature might not be easily discoverable.  I updated the [README](https://github.com/donnemartin/saws#command-history) with the following:

### Executing Shell Commands

`SAWS` allows you to execute shell commands from the `saws>` prompt.

![](http://i.imgur.com/FiSn6b2.png)

### Command History

`SAWS` keeps track of commands you enter and stores them in `~/.saws-history`.  Use the up and down arrow keys to cycle through the command history.

![](http://i.imgur.com/z8RrDQB.png)

**Comment by sesas** [comment]
Better than nothing! Thanks!

**Comment by sesas** [comment]
:+1: for the screenshots!
